---
-   name: Install python setup tools
    yum: name=python-setuptools
    tags: docker

-   name: Install Pypi
    easy_install: name=pip
    tags: docker

-   name: Install docker-py
    pip: name=docker-py
    tags: docker

-   name: Install Docker
    yum: name=docker state=latest
    tags: docker

-   name: Make sure Docker is running
    service: name=docker state=running
    tags: docker
- name: Create db container and connect to network
  docker_container:
    name: db_test
    image: "mysql:latest"
    exposed_ports:
      - 6379
    env:
      MYSQL_ROOT_PASSWORD: example

- name: Start container, connect to network and link
  docker_container:
    name: server
    image: dummypython
    links:
      - db_test
    ports:
      - "80:8080"
